name: Run Forex Bot

on:
  schedule:
    # Every 2 hours on Monday–Friday (UTC)
    - cron: '0 */2 * * 1-5'

  workflow_dispatch:  # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download state artifacts
        uses: actions/download-artifact@v4
        with:
          name: state-files
          path: ./state
        continue-on-error: true   # OK if no state yet

      - name: Ensure state directory exists
        run: mkdir -p ./state

      - name: Run trading bot
        run: python execution_resumable.py

      - name: Upload updated state
        uses: actions/upload-artifact@v4
        with:
          name: state-files
          path: ./state
