name: Run Forex Bot

on:
  schedule:
    # Every 2 hours on Monday–Friday (UTC)
    - cron: '0 */2 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Restore the latest available state
      - name: Restore state cache
        id: cache-state
        uses: actions/cache@v4
        with:
          path: ./state
          key: state-cache-v2-${{ github.run_id }}
          restore-keys: |
            state-cache-v2-

      # Safety net: if no cache was found, start fresh
      - name: Ensure state directory exists
        run: mkdir -p ./state

      - name: Log cache restore status
        run: |
          if [ "${{ steps.cache-state.outputs.cache-hit }}" != "true" ]; then
            echo "⚠️ No cache found, starting with empty state."
          else
            echo "✅ Restored state cache successfully."
          fi

      - name: Run trading bot
        run: python execution_resumable.py

      # Save updated state into unique cache for this run
      - name: Save state cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ./state
          key: state-cache-v2-${{ github.run_id }}
